/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KioskRouteImport } from './routes/kiosk'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as KioskStartRouteImport } from './routes/kiosk.start'
import { Route as KioskSearchRouteImport } from './routes/kiosk.search'
import { Route as KioskProblemsRouteImport } from './routes/kiosk.problems'
import { Route as KioskIdentifyRouteImport } from './routes/kiosk.identify'
import { Route as AdminQrcodesRouteImport } from './routes/admin.qrcodes'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminProblemsRouteImport } from './routes/admin.problems'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminAssistantRouteImport } from './routes/admin.assistant'
import { Route as AdminAssistanceRouteImport } from './routes/admin.assistance'
import { Route as KioskProductIdRouteImport } from './routes/kiosk.product.$id'
import { Route as KioskProblemIdRouteImport } from './routes/kiosk.problem.$id'
import { Route as KioskInvoiceTokenRouteImport } from './routes/kiosk.invoice.$token'

const KioskRoute = KioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const KioskStartRoute = KioskStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => KioskRoute,
} as any)
const KioskSearchRoute = KioskSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => KioskRoute,
} as any)
const KioskProblemsRoute = KioskProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => KioskRoute,
} as any)
const KioskIdentifyRoute = KioskIdentifyRouteImport.update({
  id: '/identify',
  path: '/identify',
  getParentRoute: () => KioskRoute,
} as any)
const AdminQrcodesRoute = AdminQrcodesRouteImport.update({
  id: '/qrcodes',
  path: '/qrcodes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProblemsRoute = AdminProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssistantRoute = AdminAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssistanceRoute = AdminAssistanceRouteImport.update({
  id: '/assistance',
  path: '/assistance',
  getParentRoute: () => AdminRoute,
} as any)
const KioskProductIdRoute = KioskProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => KioskRoute,
} as any)
const KioskProblemIdRoute = KioskProblemIdRouteImport.update({
  id: '/problem/$id',
  path: '/problem/$id',
  getParentRoute: () => KioskRoute,
} as any)
const KioskInvoiceTokenRoute = KioskInvoiceTokenRouteImport.update({
  id: '/invoice/$token',
  path: '/invoice/$token',
  getParentRoute: () => KioskRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/kiosk': typeof KioskRouteWithChildren
  '/admin/assistance': typeof AdminAssistanceRoute
  '/admin/assistant': typeof AdminAssistantRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/problems': typeof AdminProblemsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/qrcodes': typeof AdminQrcodesRoute
  '/kiosk/identify': typeof KioskIdentifyRoute
  '/kiosk/problems': typeof KioskProblemsRoute
  '/kiosk/search': typeof KioskSearchRoute
  '/kiosk/start': typeof KioskStartRoute
  '/admin/': typeof AdminIndexRoute
  '/kiosk/invoice/$token': typeof KioskInvoiceTokenRoute
  '/kiosk/problem/$id': typeof KioskProblemIdRoute
  '/kiosk/product/$id': typeof KioskProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kiosk': typeof KioskRouteWithChildren
  '/admin/assistance': typeof AdminAssistanceRoute
  '/admin/assistant': typeof AdminAssistantRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/problems': typeof AdminProblemsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/qrcodes': typeof AdminQrcodesRoute
  '/kiosk/identify': typeof KioskIdentifyRoute
  '/kiosk/problems': typeof KioskProblemsRoute
  '/kiosk/search': typeof KioskSearchRoute
  '/kiosk/start': typeof KioskStartRoute
  '/admin': typeof AdminIndexRoute
  '/kiosk/invoice/$token': typeof KioskInvoiceTokenRoute
  '/kiosk/problem/$id': typeof KioskProblemIdRoute
  '/kiosk/product/$id': typeof KioskProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/kiosk': typeof KioskRouteWithChildren
  '/admin/assistance': typeof AdminAssistanceRoute
  '/admin/assistant': typeof AdminAssistantRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/problems': typeof AdminProblemsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/qrcodes': typeof AdminQrcodesRoute
  '/kiosk/identify': typeof KioskIdentifyRoute
  '/kiosk/problems': typeof KioskProblemsRoute
  '/kiosk/search': typeof KioskSearchRoute
  '/kiosk/start': typeof KioskStartRoute
  '/admin/': typeof AdminIndexRoute
  '/kiosk/invoice/$token': typeof KioskInvoiceTokenRoute
  '/kiosk/problem/$id': typeof KioskProblemIdRoute
  '/kiosk/product/$id': typeof KioskProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/kiosk'
    | '/admin/assistance'
    | '/admin/assistant'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/problems'
    | '/admin/products'
    | '/admin/qrcodes'
    | '/kiosk/identify'
    | '/kiosk/problems'
    | '/kiosk/search'
    | '/kiosk/start'
    | '/admin/'
    | '/kiosk/invoice/$token'
    | '/kiosk/problem/$id'
    | '/kiosk/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kiosk'
    | '/admin/assistance'
    | '/admin/assistant'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/problems'
    | '/admin/products'
    | '/admin/qrcodes'
    | '/kiosk/identify'
    | '/kiosk/problems'
    | '/kiosk/search'
    | '/kiosk/start'
    | '/admin'
    | '/kiosk/invoice/$token'
    | '/kiosk/problem/$id'
    | '/kiosk/product/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/kiosk'
    | '/admin/assistance'
    | '/admin/assistant'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/problems'
    | '/admin/products'
    | '/admin/qrcodes'
    | '/kiosk/identify'
    | '/kiosk/problems'
    | '/kiosk/search'
    | '/kiosk/start'
    | '/admin/'
    | '/kiosk/invoice/$token'
    | '/kiosk/problem/$id'
    | '/kiosk/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  KioskRoute: typeof KioskRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kiosk': {
      id: '/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/kiosk/start': {
      id: '/kiosk/start'
      path: '/start'
      fullPath: '/kiosk/start'
      preLoaderRoute: typeof KioskStartRouteImport
      parentRoute: typeof KioskRoute
    }
    '/kiosk/search': {
      id: '/kiosk/search'
      path: '/search'
      fullPath: '/kiosk/search'
      preLoaderRoute: typeof KioskSearchRouteImport
      parentRoute: typeof KioskRoute
    }
    '/kiosk/problems': {
      id: '/kiosk/problems'
      path: '/problems'
      fullPath: '/kiosk/problems'
      preLoaderRoute: typeof KioskProblemsRouteImport
      parentRoute: typeof KioskRoute
    }
    '/kiosk/identify': {
      id: '/kiosk/identify'
      path: '/identify'
      fullPath: '/kiosk/identify'
      preLoaderRoute: typeof KioskIdentifyRouteImport
      parentRoute: typeof KioskRoute
    }
    '/admin/qrcodes': {
      id: '/admin/qrcodes'
      path: '/qrcodes'
      fullPath: '/admin/qrcodes'
      preLoaderRoute: typeof AdminQrcodesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/problems': {
      id: '/admin/problems'
      path: '/problems'
      fullPath: '/admin/problems'
      preLoaderRoute: typeof AdminProblemsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assistant': {
      id: '/admin/assistant'
      path: '/assistant'
      fullPath: '/admin/assistant'
      preLoaderRoute: typeof AdminAssistantRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assistance': {
      id: '/admin/assistance'
      path: '/assistance'
      fullPath: '/admin/assistance'
      preLoaderRoute: typeof AdminAssistanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/kiosk/product/$id': {
      id: '/kiosk/product/$id'
      path: '/product/$id'
      fullPath: '/kiosk/product/$id'
      preLoaderRoute: typeof KioskProductIdRouteImport
      parentRoute: typeof KioskRoute
    }
    '/kiosk/problem/$id': {
      id: '/kiosk/problem/$id'
      path: '/problem/$id'
      fullPath: '/kiosk/problem/$id'
      preLoaderRoute: typeof KioskProblemIdRouteImport
      parentRoute: typeof KioskRoute
    }
    '/kiosk/invoice/$token': {
      id: '/kiosk/invoice/$token'
      path: '/invoice/$token'
      fullPath: '/kiosk/invoice/$token'
      preLoaderRoute: typeof KioskInvoiceTokenRouteImport
      parentRoute: typeof KioskRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAssistanceRoute: typeof AdminAssistanceRoute
  AdminAssistantRoute: typeof AdminAssistantRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProblemsRoute: typeof AdminProblemsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminQrcodesRoute: typeof AdminQrcodesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAssistanceRoute: AdminAssistanceRoute,
  AdminAssistantRoute: AdminAssistantRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProblemsRoute: AdminProblemsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminQrcodesRoute: AdminQrcodesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface KioskRouteChildren {
  KioskIdentifyRoute: typeof KioskIdentifyRoute
  KioskProblemsRoute: typeof KioskProblemsRoute
  KioskSearchRoute: typeof KioskSearchRoute
  KioskStartRoute: typeof KioskStartRoute
  KioskInvoiceTokenRoute: typeof KioskInvoiceTokenRoute
  KioskProblemIdRoute: typeof KioskProblemIdRoute
  KioskProductIdRoute: typeof KioskProductIdRoute
}

const KioskRouteChildren: KioskRouteChildren = {
  KioskIdentifyRoute: KioskIdentifyRoute,
  KioskProblemsRoute: KioskProblemsRoute,
  KioskSearchRoute: KioskSearchRoute,
  KioskStartRoute: KioskStartRoute,
  KioskInvoiceTokenRoute: KioskInvoiceTokenRoute,
  KioskProblemIdRoute: KioskProblemIdRoute,
  KioskProductIdRoute: KioskProductIdRoute,
}

const KioskRouteWithChildren = KioskRoute._addFileChildren(KioskRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  KioskRoute: KioskRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
